services:
  - type: web
    name: the-berber-randevu
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python3 app.py"
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: THE_BERBER_ADMIN_PIN
        sync: false
      - key: THE_BERBER_PUBLIC_URL
        value: https://theberber.eu.org
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false
      - key: THE_BERBER_NOTIFY_WHATSAPP_TO
        sync: false
